function keypointsAnnotationEN = import_keypointsAnnotation(filename, dataLines)
% IMPORTFILE テキスト ファイルからデータをインポート
%  KEYPOINTSANNOTATIONEN = IMPORTFILE(FILENAME) は既定の選択に関してテキスト ファイル
%  FILENAME からデータを読み取ります。  データを cell 配列として返します。
%
%  KEYPOINTSANNOTATIONEN = IMPORTFILE(FILE, DATALINES) はテキスト ファイル
%  FILENAME の指定された行区間のデータを読み取ります。DATALINES
%  を正の整数スカラーとして指定するか、行区間が不連続の場合は正の整数スカラーからなる N 行 2 列の配列として指定します。
%
%  例:
%  keypointsAnnotationEN = importfile("C:\Users\skusano\OneDrive - MathWorks\Documents\Demo\PoseEstimation_3D\Data\keypointAnnotation\keypointsAnnotation_EN.txt", [1, Inf]);
%
%  READTABLE も参照してください。
%
% MATLAB からの自動生成日: 2021/04/01 14:21:36

%% This file automatically generated by MATLAB to read text file for
% keypoint annotation.
%% 入力の取り扱い

% dataLines が指定されていない場合、既定値を定義します
if nargin < 2
    dataLines = [1, Inf];
end

%% インポート オプションの設定およびデータのインポート
opts = delimitedTextImportOptions("NumVariables", 2);

% 範囲と区切り記号の指定
opts.DataLines = dataLines;
opts.Delimiter = ",";

% 列名と型の指定
opts.VariableNames = ["Var1", "nose"];
opts.SelectedVariableNames = "nose";
opts.VariableTypes = ["string", "char"];

% ファイル レベルのプロパティを指定
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% 変数プロパティを指定
opts = setvaropts(opts, ["Var1", "nose"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var1", "nose"], "EmptyFieldRule", "auto");

% データのインポート
keypointsAnnotationEN = readtable(filename, opts);

%% 出力型への変換
keypointsAnnotationEN = table2cell(keypointsAnnotationEN);
numIdx = cellfun(@(x) ~isnan(str2double(x)), keypointsAnnotationEN);
keypointsAnnotationEN(numIdx) = cellfun(@(x) {str2double(x)}, keypointsAnnotationEN(numIdx));
end

% Copyright 2021 The MathWorks, Inc.